### ISSUE TITLE
Write tests for verifying promotions and discounts on items added to the cart

### ISSUE THREAD

**Issue by ntewari29** [ntewari29/SuperMarketPriceManager#8]

**Comment by mslowiak** [comment]
I can handle that if needed

**Comment by ntewari29** [comment]
@mslowiak, sure and why not, I have made a few changes to the repo, let me raise a pull request later today and you can then start writing the tests on top of that.

**Comment by mslowiak** [comment]
@ntewari29 any updates?

**Comment by ntewari29** [comment]
@mslowiak yes actually, my latest implementation broke a few existing tests, trying to fix them, I couldn't spend much time on it though. Will try to make it ASAP.

**Comment by ntewari29** [comment]
@mslowiak please proceed, I raised a pull request with a few changes and a failing test
